# The name of the games
C++MAINSRCS  = run-unordered-map.cpp
C++MAINSRCS += run-map.cpp

C++FLAGS     = -std=c++11
C++FLAGS    += -Wno-sign-compare
SYSLIBS     += -lstdc++

include ../../etc/Make.rules
