# The name of the games
SRCS     = hash-table.c
SRCS    += hash-int.c
SRCS    += hash-string.c
SRCS    += hash-pointer.c
SRCS    += compare-int.c
SRCS    += compare-string.c
SRCS    += compare-pointer.c
LIB      = lib-kbench-c-alg.a
MAINSRCS = run-c-alg.c

include ../../etc/Make.rules
