# The name of the games
MAINSRCS = run-stb.c

WFLAGS   = -Wno-strict-aliasing
WFLAGS  += -Wno-pointer-to-int-cast
WFLAGS  += -Wno-unused-value
WFLAGS  += -Wno-unused-but-set-variable
WFLAGS  += -Wno-unused-function
WFLAGS  += -Wno-maybe-uninitialized
WFLAGS  += -Wno-strict-overflow
WFLAGS  += -Wno-return-type

include ../../etc/Make.rules
