# The name of the games
C++MAINSRCS  = run-mct-closed.cpp
C++MAINSRCS += run-mct-linked.cpp

INCLUDE      = -Imct
C++FLAGS     = -Wno-sign-compare
SYSLIBS     += -lstdc++ -lm

include ../../etc/Make.rules
