# The name of the games
SRCS      = tommyhash.c
SRCS     += tommyhashtbl.c
SRCS     += tommyhashlin.c
SRCS     += tommyhashdyn.c
LIB       = lib-kbench-tommyds.a
MAINSRCS  = run-fixed.c
MAINSRCS += run-linear.c
MAINSRCS += run-dynamic.c

include ../../etc/Make.rules
