# The name of the games
SRCS      = libchash.c
LIB       = lib-kbench-google.a
MAINSRCS  = run-dense.c
MAINSRCS += run-sparse.c

WFLAGS    = -Wno-parentheses
WFLAGS   += -Wno-unused-function
WFLAGS   += -Wno-address
WFLAGS   += -Wno-strict-aliasing

include ../../etc/Make.rules
