# The name of the games
SRCS        = judy.c
LIB         = lib-kbench-judy.a
C++MAINSRCS = run-jat.cpp

CFLAGS     += -Wno-parentheses -Wno-unused-but-set-variable -Wno-maybe-uninitialized
C++FLAGS   += -Wno-sign-compare
C++FLAGS   += -fpermissive
SYSLIBS    += -lstdc++

include ../../etc/Make.rules
