# The name of the games
SRCS      = hashit.c
SRCS     += hfunctions.c
LIB       = lib-kbench-hashit.a
MAINSRCS  = run-open.c
MAINSRCS += run-overflow.c
MAINSRCS += run-chain.c

include ../../etc/Make.rules
