# The name of the games
SRCS     = hashtab.c
LIB      = lib-kbench-gcc.a
MAINSRCS = run-gcc.c

DEFINES  = -DHAVE_MALLOC_H -DHAVE_STDINT_H -DHAVE_STDLIB_H -DHAVE_STRING_H

include ../../etc/Make.rules
